// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIOtUp4ThUqB0yI_PqW3kxVwCo8jxQcxA',
    appId: '1:186080757057:android:c0dba29daf16d41cea4dc0',
    messagingSenderId: '186080757057',
    projectId: 'nondriver',
    storageBucket: 'nondriver.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPxPs1MbOc5XUo9ieV04ga0_C1tI2TzZY',
    appId: '1:186080757057:ios:81ab58828fd1adfeea4dc0',
    messagingSenderId: '186080757057',
    projectId: 'nondriver',
    storageBucket: 'nondriver.firebasestorage.app',
    iosBundleId: 'com.example.ondriver',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPxPs1MbOc5XUo9ieV04ga0_C1tI2TzZY',
    appId: '1:186080757057:ios:8c04ff7d199095d8ea4dc0',
    messagingSenderId: '186080757057',
    projectId: 'nondriver',
    storageBucket: 'nondriver.firebasestorage.app',
    iosBundleId: 'com.example.ondriver',
  );
}